# Generated by Django 3.1.1 on 2021-03-30 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=155)),
                ('author', models.CharField(max_length=60)),
                ('description', models.TextField(max_length=500)),
                ('text', models.TextField()),
                ('thumbnail', models.ImageField(default='images/default.png', upload_to='images/')),
            ],
        ),
    ]
