# Generated by Django 3.1.1 on 2021-03-30 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news_list', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='category',
            field=models.CharField(choices=[('Sport', 'Sports'), ('Technology', 'Technology'), ('Culture', 'Culture'), ('Other', 'Other')], default='Other', max_length=15),
        ),
        migrations.AddField(
            model_name='news',
            name='slug',
            field=models.SlugField(default='defaultslug', max_length=255),
        ),
        migrations.AlterField(
            model_name='news',
            name='author',
            field=models.CharField(default='Author', max_length=60),
        ),
        migrations.AlterField(
            model_name='news',
            name='description',
            field=models.TextField(default='Description', max_length=500),
        ),
        migrations.AlterField(
            model_name='news',
            name='text',
            field=models.TextField(default='Text body'),
        ),
        migrations.AlterField(
            model_name='news',
            name='title',
            field=models.CharField(default='Title', max_length=155),
        ),
    ]
