# Generated by Django 3.1.1 on 2021-03-30 06:37

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('news_list', '0002_auto_20210330_0935'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='date',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2021, 3, 30, 6, 37, 19, 286006, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
