# Generated by Django 3.1.1 on 2021-03-30 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news_list', '0005_auto_20210330_0948'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='slug',
            field=models.SlugField(blank=True, null=True, unique=True),
        ),
    ]
